apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: mypage 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mypage 
    spec:
      containers:
        - name: mypage 
          image: admin16acr.azurecr.io/mypage
          ports:
          - containerPort: 8080